### PR TITLE
Rename InMemoryDataProxy.js to inMemoryDataProxy.js

### PR DESCRIPTION
**Pull request by njacques**
I've changed the filename to match reference from inMemoryDataProxyFactory.js and fix the 'module not found' error you'd otherwise get when trying to run the sample app.

### CODE REVIEW

**Comment by ahanusa** [comment]
Thanks for finding that, Nilson.  Strange thing is, it's worked for me this entire time, but glad you found it!  What version of node are you running?

**Comment by njacques** [comment]
Node v6.8.0 running on Linux. Are you running on Windows, by any chance? The file system isn't case-sensitive, which would mask the issue.

**Comment by ahanusa** [comment]
No, running on a mac.  <shrug>, glad you caught it!

**Comment by njacques** [comment]
Hmm, apparently on a Mac it [depends which filesystem you use](http://apple.stackexchange.com/questions/22297/is-bash-in-osx-case-insensitive) to format the disk, so that could possibly be the reason.

**Comment by ahanusa** [comment]
good call, that was it!

**Pull request merged**
